### ISSUE TITLE
Introduce alternative converter parameter in conversion method

### ISSUE THREAD

**Issue by tomasr78** [ConvertAPI/convertapi-js#1]
Some formats have several converters, for example, docx to pdf has three of them listed below.
It should be a possibility to set up an alternative converter from the library in the Convert method.

https://v2.convertapi.com/convert/docx/to/pdf
https://v2.convertapi.com/convert/docx/to/pdf/converter/openoffice
https://v2.convertapi.com/convert/docx/to/pdf/converter/printer

This is only an example of a convert method on how it could implement alternative converters.

Default method

convertApi.convert('docx', 'pdf', params)

with alternative converter

convertApi.convert('docx', 'pdf', 'openoffice',params)

**Comment by JonasJasas** [comment]
03d9dead347d9ce73549d194b79f99ec7c6074d9
