### ISSUE TITLE
I got .a.auth is not a function error when I use this package

### ISSUE THREAD

**Issue by msundiitalk** [ConvertAPI/convertapi-js#10]
The error message is :
`Unhandled Rejection (TypeError): convertapi_js__WEBPACK_IMPORTED_MODULE_6___default.a.auth is not a function`

The Code:
       ` import ConvertApi from 'convertapi-js'; `

        ....
        let convertApi = ConvertApi.auth({secret: 'secretCode'})
        let params = convertApi.createParams()
        params.add('file', dataTransfer.files[0]);
        let result = await convertApi.convert('docx', 'png', params)
        console.log(result);`

**Comment by woohelps** [comment]
https://github.com/ConvertAPI/convertapi-js/issues/4

as @Slavi15 said, there is no exports from convertapi-js, so 
`import ConvertApi from 'convertapi-js'; `  
doesn't work and ConvertApi is a blank object.
