### ISSUE TITLE
I got .a.auth is not a function error when I try to convert file

### ISSUE THREAD

**Issue by woohelps** [ConvertAPI/convertapi-js#11]
I got the error:
`Unhandled Rejection (TypeError): convertapi_js__WEBPACK_IMPORTED_MODULE_6___default.a.auth is not a function`

`npm i convertapi-js`

Here is my code as below:

        import ConvertApi from "convertapi-js";

        let convertApi = ConvertApi.auth({secret: 'mysecret'});  -> The error occurs line
        let params = convertApi.createParams();
        params.add('file', dataTransfer.files[0]);   -> dataTransfer.files[0] is a file object
        let result = await convertApi.convert('docx', 'png', params);
        console.log(result);

**Comment by woohelps** [comment]
https://github.com/ConvertAPI/convertapi-js/issues/4

as @Slavi15 said, there is no exports from convertapi-js, so 
`import ConvertApi from 'convertapi-js'; `  
doesn't work and ConvertApi is a blank object.

**Comment by JonasJasas** [comment]
Please try the new module version: https://www.npmjs.com/package/convertapi-js/v/1.1.0
