### ISSUE TITLE
Error response resolves as success on promise

### ISSUE THREAD

**Issue by kostas-jonauskas** [ConvertAPI/convertapi-js#13]
The promise resolves successfully even if there is an error, so we need to double-check manually if the result is successful in the "then" statement. Also, the try-catch doesn't catch an error when using ```await convertApi.convert(extension, destination, params)```. Please throw an error if there is an error.

```js  
  convertApi.convert(extension, destination, params).then(x => {
       // validation parameter and other errors go here
    }, (error) => {
      // instead of here
      throw(error);
    });
```

**Comment by JonasJasas** [comment]
https://github.com/ConvertAPI/convertapi-js/commit/2c9b9552fbdf871359c1ea12e95c6c60ea505cdd#diff-d60e0c3f656a342319be7df765ca4f05acdee8f350d619c818b2ab209851b90eR54-R55
