### ISSUE TITLE
Chrome extension file access issues

### ISSUE THREAD

**Issue by MattTheCuber** [ConvertAPI/convertapi-js#18]
Using https://unpkg.com/convertapi-js/lib/convertapi.js

I guess this is more of a feature request. I am trying to write a chrome extension that grabs some image URLs then uses this API to convert it to PDF. My problem is that the files are protected behind authorization headers. When I use `new URL` it removes the authorization headers and the request fails. I am willing to modify my local copy `convertapi.js` if needed.

I have tried (for several hours) to use the file type instead, but it looks like you need to use the actual `File` object type and I cannot get this in a chrome extension as far as I know. Because, if I try to download the files it only gives me the [downloadId](https://developer.chrome.com/docs/extensions/reference/downloads/#method-download). If you have suggestions for alternatives I would be happy to try them. Creating this issue is my last resort so hopefully there is some way I can get this to work.

**Comment by JonasJasas** [comment]
You can upload files to our file server using Fetch API:

`https://v2.convertapi.com/upload?HeaderName=Authorization&HeaderValue=BearerXXX&url=http%3A%2F%2Fexample.com%2Ffile.doc`

- `HeaderName` - sets header name
- `HeaderValue` - sets header value

Then use the uploaded file ID in the conversion request.
Read more here: https://www.convertapi.com/doc/upload

**Comment by MattTheCuber** [comment]
And what if there are multiple authorization headers?

**Comment by JonasJasas** [comment]
For such exotic scenarios, I would use FaaS (Cloudflare workers, Amazon functions) to add these headers.
Another option is to try if this Chromium fix would work: https://bugs.chromium.org/p/chromium/issues/detail?id=688906#c73
The idea is to request file to the browser and then redirect stream to our file server (use the response body as a source for the request body).

**Comment by JonasJasas** [comment]
Just found out that is not yet implemented. So for now use FaaS solution.

**Comment by MattTheCuber** [comment]
I have never heard of this FaaS solution before. Any chance you could link some documentation or a guide?

**Comment by JonasJasas** [comment]
https://workers.cloudflare.com/
https://developers.cloudflare.com/workers/examples/alter-headers/
