### ISSUE TITLE
Can not import the library

### ISSUE THREAD

**Issue by omarkhatibgg** [ConvertAPI/convertapi-js#23]
Hello,
I was trying to use the library, but I got an error that the ` is not a module.` and the import seems to be broken

here is a screenshot for the error :
![Screenshot 2024-09-19 at 01 58 55](https://github.com/user-attachments/assets/ee3770d1-65bf-433a-99a2-99af8ab57b49)

also in terminal, I got this error ` Uncaught TypeError: import_convertapi_js.default.auth is not a function.`

**Comment by JonasJasas** [comment]
Please use 1.1.9 version.
