### ISSUE TITLE
Some special characters are not rendering

### ISSUE THREAD

**Issue by rashmendis** [ConvertAPI/convertapi-js#3]
I'm trying to get the html to pdf work but some characters like ₽, ₺ are not rendering properly to the pdf. Tested with [convertapi.com/html-to-pdf](https://www.convertapi.com/html-to-pdf) as well.

**Sample Code**
```
<!DOCTYPE html>
<html>
<body>
<div>ABC</div>
<div>USD $</div>
<div>Euro €</div>
<div>UK £</div>
<div>Russia ₽</div>
<div>Russia &#x20BD;</div>
<div>Russia &#8381;</div>
<div>Turkey ₺</div>
<div>Ukraine ₴</div>
</body> 
```

**PDF Output**
<img width="175" alt="Screenshot 2020-08-27 at 10 33 45" src="https://user-images.githubusercontent.com/11315372/91386518-cb0ee480-e850-11ea-9685-469727b59e65.png">

**Comment by JonasJasas** [comment]
Hello,

sorry for the late reply, the issue with the characters is fixed.

**Comment by rashmendis** [comment]
Yes. Working now.
