### ISSUE TITLE
Problems using convertapi-js with Next.js & React.js

### ISSUE THREAD

**Issue by Slavi15** [ConvertAPI/convertapi-js#4]
Hello,
When I try to use convertapi-js in my Next.js app, the console gives me errors.

First case:

`import 'convertapi-js';`
`let convertapi = ConvertApi.auth({ secret: "secret"});`

This gives me error 4013: User credentials not set

Second case:

`import { ConvertApi } from 'convertapi-js';`
`let convertapi = ConvertApi.auth({ secret: "secret"});`

This gives me error:  Cannot read property 'auth' of undefined

Third case:

`import ConvertApi from 'convertapi-js';`
`let convertapi = ConvertApi.auth({ secret: "secret"});`

This gives me error:  convertapi_js__WEBPACK_IMPORTED_MODULE_6___default.a.auth is not a function

Thanks in advance

**Comment by JonasJasas** [comment]
Please try this example https://github.com/ConvertAPI/convertapi-js/tree/master/examples/simple and let me know about the results.

**Comment by Slavi15** [comment]
I created index.html and index.js and used the same code in the example. Everything went fine.

**Comment by Slavi15** [comment]
I found a very interesting way of solving this issue in Next.js apps. These errors are happening because convertapi-js doesn't have exports.

In _app.js:
````
useEffect(() => { 
    let script = document.createElement('script');
    script.src = 'https://unpkg.com/convertapi-js/lib/convertapi.js';
    document.getElementsByTagName('head')[0].appendChild(script);
  })
````

In the component (without importing anything from 'convertapi-js'):
```
const convertapi = ConvertApi.auth({ secret: process.env.CONVERT_API });

const params = convertapi.createParams();
params.add('file', file);

const list1 = document.getElementById('selectList1');
const list2 = document.getElementById('selectList2');

let option1 = list1.options[list1.selectedIndex].value;
let option2 = list1.options[list2.selectedIndex].value;

const result = convertapi.convert(option1, option2, params);
```

Hope this helps somebody! In React.js, instead of useEffect(() => { }), componentDidMount() is a better approach in my opinion.

**Comment by WeAreELIC** [comment]
I would also like to have this client as an ES6 module so I can use it with other JS Frameworks such as Svelte and Vue.

**Comment by JonasJasas** [comment]
I am sure that it is possible to use ConvertAPI JS library with any framework. In order to have the best compatibility and make it simple and as small as possible, we don't use modules.

**Comment by epysqyli** [comment]
Still not sure how to use convertApi in Next.js. Any suggestion would be much appreciated!

Specifically, after importing via `import 'convertapi-js'` I get `convertApi is not defined`

**Comment by JonasJasas** [comment]
Please try the new module version: https://www.npmjs.com/package/convertapi-js/v/1.1.0
