### ISSUE TITLE
Create two separated Interfaces for Secret and Token authentication.

### ISSUE THREAD

**Issue by tomasr78** [ConvertAPI/convertapi-js#5]
There are three authentication methods:

1. Secret
2. Token
3. Self-generated token and API key

To help a developer understand the code I suggest creating two different Auth Interfaces

https://github.com/ConvertAPI/convertapi-js/blob/ea02cab503c3e13a0904830c216855317f391ec4/src/convertapi.ts#L2

Used to authenticate with secret
```
    interface Credentials {
        secret: string
    }
```

Used to authenticate with `token `or `self-generated token and apikey.`  
```
 interface Credentials {
        token: string
        apikey: string
    }
```
   

https://www.convertapi.com/doc/auth

**Comment by JonasJasas** [comment]
Now constructor accepts `secret` as a string.
https://github.com/ConvertAPI/convertapi-js/commit/e2479fcc13fc664d4e3cba756a40cdd31e328528#diff-d60e0c3f656a342319be7df765ca4f05acdee8f350d619c818b2ab209851b90eR24
