### ISSUE TITLE
TypeError: p.Name.toLowerCase is not a function

### ISSUE THREAD

**Issue by devlloedy** [ConvertAPI/convertapi-js#9]
Hi I'm getting this issue TypeError: p.Name.toLowerCase is not a function at convertapi.ts:45. How to i fix this? Thanks.
![image](https://user-images.githubusercontent.com/75713279/126938475-4b9e4126-2896-4fc2-a8a1-1eab3dd9f8a6.png)

**Comment by JonasJasas** [comment]
Please provide source code how did you call `convert` method?
Provide `params` parameter value.
